### ISSUE TITLE
Support for Redis sentinel 

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#3924]
We should provide for Redis sentinel ([https://redis.io/topics/sentinel](https://redis.io/topics/sentinel)) for high availability tracker stores.

This one is a good resource how to implement it: [https://github.com/andymccurdy/redis-py#sentinel-support](https://github.com/andymccurdy/redis-py#sentinel-support)

**Comment by arthurTemporim** [comment]
@wochinge I guess these steps are needed to solve this issue:
- [ ] Update endpoints file adding `sentinel.config` file-path, and a flag about `sentinel` usage.
- [ ] Update `RedisTrackerStore` class to handle both `redis` and `redis-sentinel` configurations [here](https://github.com/RasaHQ/rasa/blob/b18e7cb596599867c04119fb70fcf42cdd546355/rasa/core/tracker_store.py#L160)
- [ ] Update documentation about `redis-sentinel` + `Rasa` usage [here](https://rasa.com/docs/rasa/api/tracker-stores/#redistrackerstore)

Is there any other main task that I am missing?

**Comment by wochinge** [comment]
@arthurTemporim Sounds good. Why an extra `sentinel.config` file? Could you not configure that in the tracker store configuration in `endpoints.yml`?

**Comment by arthurTemporim** [comment]
@wochinge After further study, I guess it is not needed, this file is important to run the `sentinel` not for using it. You're right :+1:
