### ISSUE TITLE
enable exporting tracker as json from interactive learning

### ISSUE THREAD

**Issue by amn41** [RasaHQ/rasa#4901]
**Description of Problem**:
Currently, testing custom actions can be tedious if they require a tracker with a lot of events already present. manual solution is to manually go through the conversation each time in `rasa shell`.

**Overview of the Solution**:
It'd be great if you could export your current tracker state as JSON when you hit ctrl+C in interactive learning on the command line. Then you could just `curl` that to your action server

**Definition of Done**:
- [ ] Tests are added
- [ ] Feature described the docs
- [ ] Feature mentioned in the changlog
