### ISSUE TITLE
Google Cloud Firestore as Trackerstore

### ISSUE THREAD

**Issue by matthyk** [RasaHQ/rasa#5170]
**Description of Problem**:

If you want to deploy Rasa in the Google Cloud and want to use a NoSQL database as trackerstore, there is no database to use. Already requested in the [forum](https://forum.rasa.com/t/when-developing-a-mobile-app-with-a-rasa-framework-can-use-firebase-as-a-nosql-database/24007).

**Overview of the Solution**:

Implement a Trackerstore, that uses the Firestore. This is a NoSQL cloud database, which is very affordable because you have 50000 reads and 20000 writes for free.

**Definition of Done**:

*   [ ] Tests are added
*   [ ] Feature described the docs
*   [ ] Feature mentioned in the changlog
*   [ ] Trackerstore class, that uses the firestore is implemented

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀@dakshvar22 will get back to you about it soon!✨

**Comment by MadPr0grammer** [comment]
Hi!
I would like to work on this. Can I take this up?

**Comment by federicotdn** [comment]
Hi @MadPr0grammer, thanks for your interest in this issue.

Would you mind giving a bit more context on why you need this integration in particular? Could it be possible, for example, to use an already existing tracker store implementation and host it in Google Cloud as well? The reason I'm asking is, we need to know there's a reasonable demand for this feature to be included in our repo, as we will later need to maintain it as the rest of the codebase changes. Thanks!

**Comment by MadPr0grammer** [comment]
Hi @federicotdn 

I don't really need this integration 😅. I just wanted to contribute to rasa open source (I love rasa ❤️) and was going through the list of open issues and came across this one and thought it would be a good fit for me (I have never contributed to any big opensource project and wanted to learn).

**Comment by federicotdn** [comment]
Sounds great!! Have you checked the [contributor board](https://github.com/orgs/RasaHQ/projects/23)? You may find some easy to fix issues there.

**Comment by MadPr0grammer** [comment]
Cool! I'll do that. Thanks!
