### ISSUE TITLE
Provide tracker during output_channel.send_response call

### ISSUE THREAD

**Issue by zucher** [RasaHQ/rasa#5894]
**Description of Problem**:
In some cases we want to have an access to older meta data from custom channels like exchange language stored into metadata for ex. 
https://forum.rasa.com/t/provide-tracker-during-output-channel-send-response-call/29307

**Overview of the Solution**:
Solution providing an access else at outchannel creation or on call to the current conversation tracker.

**Definition of Done**:
- [ ] Tests are added
- [ ] Feature described the docs
- [ ] Feature mentioned in the changlog

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @Ghostvv will get back to you about it soon! ✨

**Comment by wochinge** [comment]
@zucher Can you please provide an example use case for that? I'm wondering if that's something which should rather be implemented as policy / NLU component or within a custom tracker store.

**Comment by zucher** [comment]
@wochinge, find my several use cases:

-  on message reception from a channel, I'm able to detect some element like remote party language nd I store the information under metadata for later usage like the the sending to message in the native language of the user. A bi directional translation is possible in that case.

- Using an adaptive cards template I'm able to fill the domain utter custom_json with the last stored information under tracker store session directly into the connector. No need to call a specific action for that, it's generical at model usage point of view and connector point of view.

**Comment by wochinge** [comment]
> on message reception from a channel, I'm able to detect some element like remote party language nd I store the information under metadata for later usage like the the sending to message in the native language of the user. A bi directional translation is possible in that case.

So if I understand that correctly you'd handle translation from the user's language to the language the model "understands" (and back) with the channels? 🤔 

To me this seems a bit like a second way to implement custom actions 🤔

**Comment by zucher** [comment]
Hi @wochinge,

Yes the goal of one of the usage of the filter into our connector is to have a single model language with translation in/out.

As where as custom actions needs additional server to offer the capability. Our connector allow to plug Rasa to our infra without action server. Easy to deliver.
