### ISSUE TITLE
New training data format (Maturation)

### ISSUE THREAD

**Issue by degiz** [RasaHQ/rasa#6129]
Umbrella ticket for the maturation of the New Training Data Format.

We can logically split the work into parts:

Feedback on `2.0`:

- [x] NLU: intents should start with `-` as noted [here](https://www.notion.so/rasa/Feedback-on-2-0-4574eaacc0764967ac0b8b82fbc72904?d=092eb214-51e1-4125-8148-bcfa1eb4e2af#6929b68580314eb59140ff23032df35b) - #6243 

Interactive learning:
- [x] NLU: needs new YAML writer - #6252 
- [x] Core: needs new YAML writer - #6374

New features:
- [x] Add `version` field to the YAML files with training data format version - #6246
- [x] Converter tool from `1.0` to `2.0` - #6402

**Comment by tmbo** [comment]
@degiz is there a ticket for the yaml stories writer (Core)? I guess it will probably be only one writer anyways since writing really is just dumping a dict into yaml - so not really a difference between nlu and core (apart from the preprocessing needed for the blocks that need the nlu example syntax with our artificial `-`)

**Comment by degiz** [comment]
@tmbo it's a little bit trickier than just dumping the dict, bc for both the `NLU` and `Core` we use internal representation of the training data, `TrainingData` and `List[StoryStep]` respectively, they do not represent the data "as in the training data files".
All tickets are in the Issue description.
