### ISSUE TITLE
RulePolicy Todos after Rasa Open Source 2.0 alpha

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#6176]
- [ ] Refactor `RulePolicy` module -> Vova (in progress)
- [x] Refactor the [hack](https://github.com/RasaHQ/rasa/blob/6d60ca542d04f0534b88c531e35e8852d3dfc8b0/rasa/core/domain.py#L676) for the featurization of the deactivated form -> Vova (part of e2e PR)
- [x] [rename `Form` event to `Loop`](https://github.com/RasaHQ/rasa/issues/6409)
- [x] Decide whether forms and loops can use the the same `Form` / `Loop` event or if they should use different one (one event is fine)
- [x] decide whether to add field `active_loop` to `tracker` dict and to deprecate `active_form`
- [x] [make it possible in the `FormAction` to use a custom action to ask for the next requested slot](https://github.com/RasaHQ/rasa/issues/6185)
- [ ] Check how to represent confidence in[ Fallback classifier ](https://github.com/RasaHQ/rasa/blob/49270070f1d8baab4c177cb8b8c4c3643775a183/rasa/nlu/classifiers/fallback_classifier.py#L58)
- [x] [Documentation](https://github.com/RasaHQ/rasa/issues/6184) -> Tobi
- [x] Update warnings / changelog to include link to rules documentation
- [x] [make it easier to validate extracted slots in the SDK](https://github.com/RasaHQ/rasa-sdk/issues/238)

**Comment by Ghostvv** [comment]
For documentation:

- describe how to use custom `required_slots` flow. Validate action can return which next slot is requested and also can return `SlotSet(REQUESTED_SLOT, None)` indicating that a form should be deactivated
- mention that external events that trigger smth should be defined as rule snippets

**Comment by wochinge** [comment]
@Ghostvv What's the state of the refactoring? Did you do that as part of the `negative rules` branch? What about the other open todos?

**Comment by wochinge** [comment]
ah, you probably had a couple of stories?

**Comment by Ghostvv** [comment]
started the final refactor today, I plan to finish it tomorrow, it'll have to be part of e2e PR

**Comment by wochinge** [comment]
- Should we rename the form event internally? It's already renamed in the YAML data (`active_loop`) -> I think we're fine for now
- Do we need separate loop / form event -> I think no.
- Refactor the hack for the featurization of the deactivated form - did you do you that @Ghostvv ?
- Check how to represent confidence in Fallback classifier - What would a different representation achieve @Ghostvv ?

**Comment by Ghostvv** [comment]
> Should we rename the form event internally?

I think we should

**Comment by Ghostvv** [comment]
> Refactor the hack for the featurization of the deactivated form

yes it is part of e2e PR

**Comment by Ghostvv** [comment]
> Check how to represent confidence in Fallback classifier - What would a different representation achieve

it should mimic the fact how confident we are that it is indeed fallback

**Comment by m-vdb** [comment]
@wochinge do we want any of this to go into 2.0.0a2, this Friday?

**Comment by wochinge** [comment]
There is no user facing change in there so we don't need it for the second alpha

**Comment by wochinge** [comment]
> Tobi: Should we rename the form event internally?

> Vova: I think we should

**Comment by Ghostvv** [comment]
> How about Do we need separate loop / form events ? I think there is currently no need for that.

no, I think we need only loop event, how complicated is it to change in rasa x? we're preparing special version for 2.0 anyhow, right?

nlu fallback is not urgent

**Comment by wochinge** [comment]
Closing this as it's done

**Comment by wochinge** [comment]
> nlu fallback is not urgent

i didn't create an issue for it now - I think we should do so when we actually have the need for it.

**Comment by Ghostvv** [comment]
> we actually have the need for it.
what do you mean????
We *actually* need it now, but due to that fact that we don't have time for it, it's not urgent

**Comment by Ghostvv** [comment]
I'll create an issue for it

**Comment by Ghostvv** [comment]
https://github.com/RasaHQ/rasa/issues/6685
