### ISSUE TITLE
Rename `FORM_PREFIX` to `ACTIVE_LOOP_PREFIX`

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#6464]
Follow up issue from https://github.com/RasaHQ/rasa/issues/6409:

The `FORM_PREFIX` (see [here](https://github.com/RasaHQ/rasa/blob/43267974f93287eea8dcc5c086c777755025aae7/rasa/core/training/structures.py#L33) should be renamed to `ACTIVE_LOOP_PREFIX` with a value `active_loop: `. 

**Todos**
- [ ] rename 
- [ ] make sure the old prefix is deprecated
- [ ] adapt the docs
- [ ] make sure interactive learning still works as expected
- [ ] Collect Rasa X implementations in an issue (e.g. extend this [one](https://github.com/RasaHQ/rasa/pull/6439)). The `FORM_PREFIX` is used in the story view / end-to-end story view

**Comment by degiz** [comment]
@tmbo since you've just worked on that, do we have yaml e2e stories that test the forms?

**Comment by tmbo** [comment]
we don't have them yet, but I think adding an attribute that can be used instead of the `form` prefix is the way to go for now

**Comment by wochinge** [comment]
Do we want this for the alpha 3 @tmbo @degiz ?

**Comment by tmbo** [comment]
the implications of this issue are that you cant use story tests when you are using any loops right?

**Comment by Ghostvv** [comment]
`form_prefix` is deprecated, do we need to rename it?

**Comment by Ghostvv** [comment]
the new `RulePolicy` doesn't use it

**Comment by wochinge** [comment]
Ah, we don't need it because of the new tracker featurization, correct?

**Comment by Ghostvv** [comment]
rather, the new `applied_events`

**Comment by wochinge** [comment]
Yes, that's what I mean. Then we can leave this as it is for old markdown.
