### ISSUE TITLE
New training data format - remaining items

### ISSUE THREAD

**Issue by degiz** [RasaHQ/rasa#6475]
Remaining items of the new training data format to work on before the `2.0 RC1`:

- [x] Change training data version warning to be a debug log #6361  
- [x] Parser should throw warning for deprecated entity annotation syntax #6365. **Update**: Un-deprecating this instead.
- [x] Fix bugs of `rasa data convert` command ([list](https://docs.google.com/document/d/1LNzf4ZLefdOI-bFy4lzLTpvwT5CWbE9a2NZW45FtPCU/edit))  #6505
- [x] `rasa data convert` should be able to convert forms and warn about the `FormPolicy` deprecation  #6501
- [x] Make sure one file can have all: NLU + Stories. Domain is out of it atm because of common `responses` key. #6566 

- [x] Make `metadata` from `nlu.yaml` available in NLU components #6602 
- [x] Bug with `rasa data split nlu` #6588
