### ISSUE TITLE
Post-RC1 Training data format items

### ISSUE THREAD

**Issue by degiz** [RasaHQ/rasa#6638]
- [x] `rasa train nlu` and Domain #6635 
- [x] make `StoryReader::read_from_file` synchronous #6641
- [x] Converter tool not working for E2E stories #6716 
- [x] Test stories don't work if they aren't in the end-to-end format #6732 
- [x] StoryMarkdownToYamlConverter fails to convert entity annotation in e2e story #6867

**Comment by wochinge** [comment]
I close this @degiz as all todos are done
