### ISSUE TITLE
Bring e2e in *for real* left-overs

### ISSUE THREAD

**Issue by evgeniiaraz** [RasaHQ/rasa#6670]
**What's left to do?** _Reading in e2e data_ 

*   <span class="error">[x]</span> Bring back YAML reading for end-to-end data

Research

*   <span class="error">[x]</span> Store in trackers whether intent / text were used to predict next action
*   <span class="error">[x]</span> In prediction, get the tracker history up to the current state depending on what action was predicted from (get the `intent/text` in corresponding steps)
*   <span class="error">[x]</span> figure out the condition when TED should use text or intent
*   <span class="error">[x]</span> TEDPolicy vs RulesPolicy: figure out what to do when TED uses text input, but rules predict an action based on intent
*   <span class="error">[x]</span> TEDPolicy vs RulesPolicy: what to do with nlu_fallback
*   <span class="error">[x]</span> create and test on edge cases
*   <span class="error">[x]</span> Make some mixed test stories to check it works (they can be Sara based)
*   <span class="error">[x]</span> 4D Tensors
*   <span class="error">[x]</span> Add utterance transformer to TED;
*   <span class="error">[x]</span> Ability to exclude the output of an NLU featurizer from being used for training and inference
*   <span class="error">[x]</span> increase test coverage of state and tracker featurizers
*   <span class="error">[x]</span> bring entities into TED [https://github.com/RasaHQ/research/issues/121](https://github.com/RasaHQ/research/issues/121)
*   <span class="error">[x]</span> remove fake features, and use 4d-3d converter instead
*   <span class="error">[x]</span> check if training entities in DIET is still working [https://github.com/RasaHQ/rasa/issues/7289](https://github.com/RasaHQ/rasa/issues/7289)
*   <span class="error">[x]</span> nuke from orbit entity labels from text as user input
*   <span class="error">[x]</span> pass entities extracted by ted to tracker [https://github.com/RasaHQ/rasa/pull/7443](https://github.com/RasaHQ/rasa/pull/7443)
*   <span class="error">[x]</span> create e2ebot example that makes sense
*   <span class="error">[x]</span> docs!!!!

Engineering

*   <span class="error">[x]</span> Bot utterances #6410
*   <span class="error">[x]</span> policies return events [https://github.com/RasaHQ/rasa/issues/7039](https://github.com/RasaHQ/rasa/issues/7039)
*   <span class="error">[x]</span> Check what model/components needs to be trained when `rasa train` is executed. Make sure to cover all scenarios: no NLU data, but NLU pipeline configured; no data at all; NLU data, but no NLU pipeline; etc. add warning/error if `rasa train core` is called on stories with e2e data [https://github.com/RasaHQ/rasa/issues/7129](https://github.com/RasaHQ/rasa/issues/7129)
*   <span class="error">[x]</span> Make sure the stories are printed correctly [https://github.com/RasaHQ/rasa/issues/7130](https://github.com/RasaHQ/rasa/issues/7130)

Post release:

*   <span class="error">[x]</span> fix Story structure validation [https://github.com/RasaHQ/research/issues/114](https://github.com/RasaHQ/research/issues/114)
*   [ ] Test the system
*   <span class="error">[x]</span> factor out combining sparse/dense and sequence/sentence features into re-usable layer components #7187
*   [ ] refactor tf helper methods of ted and diet
*   [ ] implement test entities extracted by TED, e.g. via rasa test. [https://github.com/RasaHQ/rasa/issues/7578](https://github.com/RasaHQ/rasa/issues/7578)
*   <span class="error">[x]</span> "auto" fill slots by entities extracted by TED
*   <span class="error">[x]</span> use bilou tags in TED [https://github.com/RasaHQ/rasa/issues/7579](https://github.com/RasaHQ/rasa/issues/7579)
*   [ ] predict entity roles/group in TED [https://github.com/RasaHQ/rasa/issues/7580](https://github.com/RasaHQ/rasa/issues/7580)
*   [ ] create "smart" retraining heuristics [https://github.com/RasaHQ/rasa/issues/7581](https://github.com/RasaHQ/rasa/issues/7581)
*   [ ] fix `rasa test` [https://github.com/RasaHQ/rasa/issues/7677](https://github.com/RasaHQ/rasa/issues/7677)
*   <span class="error">[x]</span> Add `split_entities_config` to `TEDPolicy` [https://github.com/RasaHQ/rasa/issues/7707](https://github.com/RasaHQ/rasa/issues/7707)
*   [ ] Warn users if their tests contain bot utterances not found in training data [https://github.com/RasaHQ/rasa/issues/8074](https://github.com/RasaHQ/rasa/issues/8074)

**Comment by wochinge** [comment]
@Ghostvv I guess bot utterances have the highest priority as a next step?

**Comment by Ghostvv** [comment]
yes, then, we can actually run e2e bots

**Comment by joejuzl** [comment]
Added this to 2.2 milestone, I think this issue provides enough of an overview that we don't need the e2e milestone.

**Comment by m-vdb** [comment]
Closing as won't do for now
