### ISSUE TITLE
Pre-2.0 release TODOs

### ISSUE THREAD

**Issue by mprazz** [RasaHQ/rasa#6781]
This issue aggregates all TODOs pre-2.0 release, so we're sure everything is in order before the release.

**TODO**:
- [x] remove the mentions of `2.0.0rc2` in the docs
- [x] double-check / find any remaining `TODO`s in the docs / code

**Sanity checks**:
- [x] pip installation
- [x] build from source + poetry installation
- [x] rasa init completes without errors
- [x] train a model
- [x] check basic commandline (`train` / `test` / `run` / `shell` / `interactive`)
- [x] version upgrade (1.x --> 2.x)

**Comment by m-vdb** [comment]
@mprazz @tmbo since we're doing a code freeze for 2.0 on Monday, I was wondering if we have a plan to do a QA on Rasa Open Source. It's the first time we are doing this, right?

**Comment by mprazz** [comment]
I'd be up for doing some QA on 2.0! 🚀 I've only ever done super basic testing on Rasa Open Source though (just making sure installation works, p.e.) so I think I would need some help putting together a test plan 😅

**Comment by mprazz** [comment]
Mentions of `2.0.0rc4` being removed from the docs on this PR #6945

**Comment by tmbo** [comment]
@mprazz anything you'd like to do before the release on this one?

**Comment by mprazz** [comment]
@tmbo Not anymore, from my side it looks good! I'll re-check once the package is out 😊
