### ISSUE TITLE
Release 2.1

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#7224]
**Todos**
- [x] Cut SDK release
- [x] Merge 2.0.x to `master` (yes, I also notified PR owners of PRs which still point to `2.0.x`)
- [x] `make release`
- [x] Bump minimum compatible model version due to https://github.com/RasaHQ/rasa/pull/7136
- [ ] Release

**Comment by wochinge** [comment]
I will also cut it, right? @mprazz

**Comment by mprazz** [comment]
I thought you had nominated yourself to do it @wochinge, sorry if that wasn't the case! If you're okay with cutting it too (if you have the time), go for it, otherwise we can find someone else, no worries at all 😊

**Comment by wochinge** [comment]
Wasn't sure if I just coordinate or also release it. Will also cut it then 👍

**Comment by mprazz** [comment]
I'm available if you need any help anyway 😊
