### ISSUE TITLE
Create endpoint for cross-validation

### ISSUE THREAD

**Issue by wochinge** [RasaHQ/rasa#7408]
Create an endpoint for running a cross-validation as described in the implementation proposal for intent insights [here](https://www.notion.so/rasa/Implementation-Proposal-ff4f5cb9c37e43edac4552647af7dbc2#c060672e87cd4fd891cb1643b76b96a1).

**Todos**:
- [ ] Update API spec
- [ ] add endpoint to run cross-validation
   - by default it's a synchronous call and the response / error is returned in the response payload
   - If a callback URL is passed as query param, then the server should return immediately. The result (and potential error!) of the cross-validation is passed to the caller by calling the callback
   - We need to make sure that the synchronous cross-validation doesn't block other calls. We can e.g. do this by using `run_in_executor` as we do it for the training
- [ ] consider adding a start / end datetime to the cross-validation result. This would be useful for Rasa X (especially when reading this files from disk in local mode), to see on which data the cross-validation results are based upon
