### ISSUE TITLE
Prototype Rasa 3.0 Architecture

### ISSUE THREAD

**Issue by joejuzl** [RasaHQ/rasa#8419]
Following on from discussions about a new Rasa OS architecture for 3.0:

- [Initial concept](https://www.notion.so/rasa/Rasa-Project-26915237c1c74d578af4a44f0df95755)
- [Discussion of current problems](https://www.notion.so/rasa/Rasa-Open-Source-Architecture-Sync-62f864267188476d9108cdeab2b6a5c3)
- [Exploration of related frameworks](https://www.notion.so/rasa/Workflow-Frameworks-Comparison-429eb61f58184be9b0da0280409ceec1#4bd180db123b43e69996cf658935706e)

We would like to build a prototype to assess the new proposed graph architecture.

### Must have:
* train NLU only based on current model config
* train entire model (core + NLU) based on current model config (including e2e)
* load and persist model
* do action predictions
* implement caching / fingerprinting for training
* users are able to speak to model via input channel (only the entire model, not NLU-only)

### Nice to have:
* extract + deduplicate policy featurization

### Don't need: 
* `rasa test` , `rasa interactive` 

## Implementation details
Following on from a "protoprototype" we have decided to use [Dask](https://dask.org/) for the prototype.
Dask allows for lightweight task graphs to be created and then run on arbitrary backends (e.g. single thread, multi-process, distributed cluster). It also includes a huge amount of plug and play functionality which can all be used optionally.
It seems to fit the balance of providing a lot of useful hard-to-do functionality, but not being too heavyweight or opinionated. Rather than being a full framework, it is a collection of useful related utilities.

## TODO
- [x] Prototype for the prototype. Initial sanity check and exploration to determine whether a full prototype is possible.
- [x] [Train NLU model](https://github.com/RasaHQ/rasa/issues/8408)
- [ ] [Derive training graph from current NLU config](https://github.com/RasaHQ/rasa/issues/8409)
- [ ] [Train entire model](https://github.com/RasaHQ/rasa/issues/8410)
- [ ] [Make action predictions with graph model](https://github.com/RasaHQ/rasa/issues/8412)
- [ ] [Derive training graph from current model config](https://github.com/RasaHQ/rasa/issues/8411)
- [ ] [Derive prediction graph from training graph or current config format](https://github.com/RasaHQ/rasa/issues/8414)
- [ ] [Persist and load model trained from graph](https://github.com/RasaHQ/rasa/issues/8404)
- [ ] [Implement caching / fingerprinting for training](https://github.com/RasaHQ/rasa/issues/8405)
- [ ] [Integrate graph model in server](https://github.com/RasaHQ/rasa/issues/8406)
- [ ] [Test with realistic dataset](https://github.com/RasaHQ/rasa/issues/8488)
- [ ] [Explore partial dataset loading for NLU graph](https://github.com/RasaHQ/rasa/issues/8407) (Thomas)

## Time estimation: 4 weeks
