### ISSUE TITLE
Architecture Prototype: profile memory for new tracker featurization

### ISSUE THREAD

**Issue by twerkmeister** [RasaHQ/rasa#8593]
**Description**:
As part of the architecture prototype, tracker featurization was changed from featurizing each history window over the conversation to featurizing a conversation once and then pulling the features for history windows from that already featurized state. Potentially this change already saves a lot of memory and would allow us to handle much larger datasets for e2e. To better understand what other steps are needed to support sizable datasets such as multiwoz or advising, we should run some memory profilings with this new featurization style.

**Definition of Done**:
- [x] run benchmark for e2e baseline - how many stories can we handle on current main branch
- [ ] run benchmark for e2e new - how many stories can we handle with this new architecture?
- [ ] figure out which parts consume the most memory: How much goes to messages, message features, trackers, etc.

**Comment by twerkmeister** [comment]
Here's the status for the [current main branch](https://github.com/RasaHQ/rasa/tree/c8e6c6bddb1552af29e17c056af2d9324878b057):

Seems the biggest bottle neck for now sits with the tensorflow model code. From the 8500 stories in multiwoz, we can handle somewhere between 750 and 1022 stories on an nvidia K80 with 12 GB GPU memory before running into out of memory on the GPU. This represents around 9-12% of the dataset. I didn't look for a more specific number, as it will probably vary depending on the config and the dataset. In short, we are still a factor of 10 away to fit multiwoz with a normal config onto a decent gpu. 

I assume we should reconsider the structure of the model. Letting the model grow with each and every possible response, does not seem to be a scalable solution. Right now we end up with tensors of sizes like [49038, 79, 128] that take up ~ 2GB of GPU ram for a single tensor:

`Resource exhausted:  OOM when allocating tensor with shape[49038,79,128] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc` 

`49038 * 79 * 128 * 4(bytes) / 2^30 = 1.84`

current config:
```yaml
language: en

pipeline:
  - name: "SpacyNLP"
    model: "en_core_web_md"
  - name: "SpacyTokenizer"
  - name: "SpacyFeaturizer"
  - name: "CountVectorsFeaturizer"
    analyzer: "char_wb"
    min_ngram: 3
    max_ngram: 3

policies:
  - name: TEDPolicy
    max_history: 5
    epochs: 10
    batch_strategy: sequence
```

The main memory is not the bottle neck here:
#### run with 9 percent of stories (interrupted by me after a couple epochs)
![multiwoz-9p-main-spacy](https://user-images.githubusercontent.com/1107341/118493541-85b57e80-b721-11eb-94e1-e3141687eee4.png)

#### run with 12 percent of stories (crashed during first epoch due to out of memory on gpu)
![multiwoz-12p-main-spacy](https://user-images.githubusercontent.com/1107341/118493616-95cd5e00-b721-11eb-8b8d-c8dba26ffb7c.png)

Not sure why in this case the main memory usage is so much higher than for 9 percent of the data. However, it doesn't grow like that if you take all data:

#### run with 100 percent of stories (crashed during first epoch due to out of memory on gpu)
![multiwoz-main-3-spacy](https://user-images.githubusercontent.com/1107341/118493961-f2c91400-b721-11eb-8008-61ddfda34cc1.png)
