### ISSUE TITLE
Update tracker store to enable storing messages in Firebase Realtime Database

### ISSUE THREAD

**Issue by Thirunayan22** [RasaHQ/rasa#8642]
**Description of Problem**:
  

The tracker method is an essential part for Rasa users when they want to store conversations between the bot and the user. But presently tracker store class in rasa core supports for only InMemory, SQL, Redis and DynamoDB type of tracker storage medium, but there is not default tracker store support for **Firebase Realtime Database**. And this issue has been discussed in [rasa forums](https://forum.rasa.com/t/custom-tracker-to-save-conversation-history-into-firebase-firestore/35432) as well where the developers must implement a custom tracker store if they want to use Firebase Realtime Database.

**Overview of the Solution**:

The solution is to create a default extensible firebase real-time database tracker store class in tracker_store.py. This tracker store class will implement the default save() ,retrieve() and keys() methods.

**Definition of Done**:

 What needs to be there to consider this feature as done?
- [ ] Implement firebase realtime database tracker store in tracker_store.py
- [ ] Feature described in docs
- [ ] Created pull request

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @lty4 will get back to you about it soon! ✨
