### ISSUE TITLE
Async trackerstore support

### ISSUE THREAD

**Issue by leonidas-tolias** [RasaHQ/rasa#8774]
**Description of Problem**: Currently, the trackerstore interface uses synchronous calls to save and retrieve conversations. This leads to performance issues as any non-memory trackerstore will use network calls and block the event loop.

**Overview of the Solution**: To resolve, there needs to be an update of all uses of the trackerstore override endpoints (save, retrieve, keys, etc) to conditionally await the results of these function in the case that they have been overridden with async functions.

**Definition of Done**: Feature will be considered complete when we can register a trackerstore with either sync or async override functions.

*   [ ] Tests are added
*   [ ] Feature described the docs
*   [ ] Feature mentioned in the changelog

**Comment by leonidas-tolias** [comment]
I'm working on submitting a pr to implement this functionality

**Comment by sara-tagger** [comment]
Thanks for submitting this feature request 🚀 @kalkbrennerei will get back to you about it soon! ✨

**Comment by wochinge** [comment]
@leonidas-tolias That definitely seems worth doing. One thing we have to consider is that users might be using custom tracker stores which aren't `async` yet. These should continue to work (but raise a deprecation message) until the next major (3.0.0). I think before you get started implementing it would be nice if you could outline the details of the change as comment in this issue as this is quite a sensitive and big change. Thank you 🙌🏻

**Comment by leonidas-tolias** [comment]
Hey, for backwards compatibility I mirrored the approach used with FailSafeTrackerStore and created a new wrapper class which checks if its child trackerstore has the save/retrieve/etc functions implemented as async or normal functions and calls them with await (or not) accordingly.  
The remaining changes were just to add an await everywhere the save/retrieve calls are made (mainly in processor.py, server.py) and to have agent.py create an AwaitableTrackerStore(FailSafeTrackerStore(tracker_store)) at startup.  In my testing so far, this seems to work fine with both async and sync trackerstore implementations. 
Implementation is mostly done, just fighting my firms internal dependency systems to get all the tests to run : ), after which I can submit a PR.  Let me know if you'd prefer some other approach.

**Comment by wochinge** [comment]
>  I mirrored the approach used with FailSafeTrackerStore and created a new wrapper class which checks if its child trackerstore has the save/retrieve/etc functions implemented as async or normal functions and calls them with await (or not) accordingly.

Slick approach! Wondering if that makes the class structure a bit too nested. Anyway, we can iterate on that in the PR comments then 🚀 

Excited for your change! 💯

**Comment by leonidas-tolias** [comment]
opened a PR here: https://github.com/RasaHQ/rasa/pull/8854
I put this issue number in the PR title, is there something else I need to do to link the pr to this issue?

**Comment by melindaloubser1** [comment]
Closed by https://github.com/RasaHQ/rasa/pull/10696
