### ISSUE TITLE
PR and review tracking

### ISSUE THREAD

**Issue by tttthomasssss** [RasaHQ/rasa#8811]
As part of assessing a new process around reviewing PRs (see [#156](https://github.com/RasaHQ/research/issues/156)), we want to record and track some metrics around the PR review process.

Track PRs and reviews:
* Time it takes to review a PR
* Size of PRs

Investigate whether GitHub offers tooling to record the above.

**Defintion of done**
- [x] PR size, PR merge time, and PR owner is available in Metabase verified (**result**: PR review time isn't being tracked yet)
- [x] Tracking PR review requests has been added so we can track time from review requested to review submitted ([PR here](https://github.com/RasaHQ/gcloud-functions-telemetry/pull/60))
- [x] Metabase dashboard for research team PR size created ([check it out](https://metabase.rasa.com/question/1120))
- [x] Metabase dashboard for research team PR review time created  ([check it out](https://metabase.rasa.com/question/1121))
- [x] Feedback from research team on first draft of dashboards is collected (early feedback [here](https://github.com/RasaHQ/rasa/issues/8811#issuecomment-866903979), another round of feedback can follow once enough data for review requests has been collected).

**Comment by tttthomasssss** [comment]
Some stats around PRs (e.g. sizes, merge times) are already recorded on Metabase:

* https://metabase.rasa.com/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjoyLCJxdWVyeSI6eyJzb3VyY2UtdGFibGUiOjI2MX0sInR5cGUiOiJxdWVyeSJ9LCJkaXNwbGF5IjoidGFibGUiLCJ2aXN1YWxpemF0aW9uX3NldHRpbmdzIjp7fX0=
* https://metabase.rasa.com/question/931

**Comment by koernerfelicia** [comment]
Saw this on the tensorflow repo today, think it's pretty neat:

<img width="866" alt="Screenshot 2021-06-09 at 09 45 12" src="https://user-images.githubusercontent.com/45405119/121314289-7f24bc00-c907-11eb-81f9-aa8c395b05b4.png">

Looks like they used something like [this tool](https://github.com/apps/pull-request-size).

**Comment by samsucik** [comment]
Given Thomas's thoughts from above, I'd just take out "setup some reporting for only the research team" and make it a separate issue, along with the (currently implicit) bit that is to actually implement collecting the things we find aren't collected currently but we think can be added.

**Comment by samsucik** [comment]
I created a [simple Metabase question for tracking the **PR size**](https://metabase.rasa.com/question/1120).

While we talked about different ways of defining the size of a PR, there's only so much information we actually have about a PR, and so I went with a simple definition that is: `additions + deletions` (in terms of LoC).

However, in the same Metabase question, I also added a more speculative measure of size as an example of what we could also do. The definition I went with is: `(additions + 0.5*deletions) * (1 + min(changed_files, 50)/50)`. The idea is to:
1. give more weight to added code than to code that got removed
2. weigh up a PR that's scattered over too many files

**Comment by samsucik** [comment]
As for tracking PR review time, [this question](https://metabase.rasa.com/question/931) only tracks the time between the final PR approval and the actual merge. For PR reviews, [the only info in Metabase](https://metabase.rasa.com/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjoyLCJxdWVyeSI6eyJzb3VyY2UtdGFibGUiOjE5NjJ9LCJ0eXBlIjoicXVlcnkifSwiZGlzcGxheSI6InRhYmxlIiwidmlzdWFsaXphdGlvbl9zZXR0aW5ncyI6e319) is about when a review was submitted, but we lack info about how long the review took.

Strictly speaking, it's hard/impossible to track how much time a reviewer has spent reviewing a PR. The best proxy we can currently get (with the kinds of events that Github tracks) is the time from when a particular review was **requested** to when it was submitted. For this, we need to start tracking PR review requests. And so this is what [my new PR](https://github.com/RasaHQ/gcloud-functions-telemetry/pull/60) does 🙂 Once it's merged, we'll know for each review request when it was created, potentially retracted or completed, and we'll be able to link it (in Metabase queries) with info about actual PRs and about PR reviews.

**Comment by samsucik** [comment]
**Ideas for possible improvements to PR size tracking** 💡 (inspired by [this discussion](https://rasa-hq.slack.com/archives/C8LEHMTAM/p1624265878327200); meant to be tackled in separate issues)
1. Treat changes to tests/docs differently (how differently is up for discussion)
1. Be able to view PR size cleaned from the "duplicated PRs", e.g. when small PRs targeting a feature branch get reviewed and merged, and then a "duplicit" PR is created to merge the feature branch into `main`.

**Comment by samsucik** [comment]
Great news: PR review requests are now tracked [here](https://metabase.rasa.com/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjoyLCJxdWVyeSI6eyJzb3VyY2UtdGFibGUiOjE5OTd9LCJ0eXBlIjoicXVlcnkifSwiZGlzcGxheSI6InRhYmxlIiwidmlzdWFsaXphdGlvbl9zZXR0aW5ncyI6e319), meaning that I can create a Metabase question to track review time 🤩

**Comment by samsucik** [comment]
Bad news: We can't retrieve historical information (more detail [here](https://rasa-hq.slack.com/archives/C36SS4N8M/p1624464890138200?thread_ts=1624276952.057500&cid=C36SS4N8M), though the real reason remains unknown), so only future reviews can be tracked for now.

**Comment by samsucik** [comment]
Closing this now, with a followup issue now living [here](https://github.com/RasaHQ/research/issues/160).
