### ISSUE TITLE
Make it possible to OR slot values - Implementation

### ISSUE THREAD

**Issue by joejuzl** [RasaHQ/rasa#8933]
**Description of Problem**:
Background: https://github.com/RasaHQ/rasa/issues/7715
Proposed Solution: https://www.notion.so/rasa/Make-it-possible-to-OR-slot-values-4abdf1b6632c4bb2881d2057b58ca335

Summary:
We want to be able to use `or` for `slot_was_set` steps in stories.
It currently only works for `intent` steps.

**Todo**:
- updating the story schema `rasa/shared/utils/schemas/stories.yml`
- updating `YAMLStoryReader`
    - `_parse_or_statement`
- updating `StoryStepBuilder`
    - adding a `slot_was_set` equivalent to `add_user_messages`
- make sure `rasa.shared.core.training_data.visualization` is updated for Rasa X story visualisation

**Example Story**:
```
- story: tell name bob or joe
  steps:
  - intent: greet
  - action: utter_greet
  - intent: tell_name
  - or:
    - slot_was_set:
        - name: joe
    - slot_was_set:
        - name: bob
  - action: utter_generic_hi
```

**Definition of Done**:
- [ ] `or` functionality added for `slot_was_set` events
- [ ] Rasa X visualisation compatibility  
- [ ] Tests are added
- [ ] Feature described the docs
- [ ] Feature mentioned in the changelog
