### ISSUE TITLE
E2E Evaluation - Milestone 1 & 2

### ISSUE THREAD

**Issue by dakshvar22** [RasaHQ/rasa#9561]
Milestone document - https://www.notion.so/rasa/e2e-project-milestone-meeting-1-af47a931cefd4c53a017c1b395f6b1e6

Tasks for getting started with at least one round of experiment (either locally or on the automated infrastructure)

By 14/09/2021:

- [x] [Brainstorming conversation phenomena](https://www.notion.so/rasa/e2e-project-milestone-meeting-1-af47a931cefd4c53a017c1b395f6b1e6#df37d663f38c4751a40a683c867b5098)
- [x] [Setting up workflow locally for all the team members and optionally the person managing the user simulator](https://github.com/RasaHQ/research/issues/178)
- [ ] [Finalize boteval config to be used](https://github.com/RasaHQ/research/issues/182) @dakshvar22 
- [x] Get the initial version of the bot ready @dakshvar22 
    - [x] Add stories
    - [x] (NEW) fix story/intent issues @JEM-Mosig 
    - [x] (NEW) add fallback @JEM-Mosig 
- [x] #9570

By 17/09/2021:
- [ ] First concrete analysis template that should be used in each round of experiment. This will be iterated upon as we do more experiments.
- [x] Come up with a way to uniquely identify simulated conversations according to the round they were generated in.
- [ ] Write a script to simulate whatever the PR was supposed to do but locally.
- [ ] Write the protocols for the teams to follow when improving their bot.
     - [ ] Make sure it includes how to make sure that whatever was fixed in previous rounds is not unfixed

**Comment by JEM-Mosig** [comment]
Closing this in favor of new issues (we need to use GPT-3 differently, see [new workflow](https://www.notion.so/rasa/Weizenbot-GPT-3-User-Simulation-for-SuperAirlineBot-600332a5607d4aff8ad0e583fffa22c4#3d4077c020214e1b8b0bdde09c979f71))
